# Application Configuration

# Server
server.port=${SERVER_PORT:8080}
spring.application.name=AEye-Systems

# prompt
prompt.food_analyzer=food_analyze_prompt
api.model = remote

# Remote API configuration
api.remote.key=AIzaSyDqshbeRzeILhSGc1WDpi94guUMsVhcVfk
api.remote.url=https://generativelanguage.googleapis.com
api.remote.model=gemini-3.1-flash-lite-preview

# Local Ollama API configuration
api.local.url=http://localhost:11434
api.local.model=llava

# Gemini API
gemini.model=gemini-3.1-flash-lite-preview
gemini.api.key=AIzaSyDqshbeRzeILhSGc1WDpi94guUMsVhcVfk

# Logging
logging.level.edu.farmingdale.CSC490=DEBUG
logging.level.org.springframework.web=INFO

# Database Configuration (if using H2 in-memory database)
spring.datasource.url=jdbc:h2:mem:testdb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=


# JPA/Hibernate Configuration
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
# JPA - set to none since Firebase handles your database
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true


# H2 Console (for development only)
spring.h2.console.enabled=true

# Firebase
firebase.config.path=firebase-key.json
FIREBASE_API_KEY=AIzaSyC0qbR3juQh85AdwivHAHe0XCVNugSueGo
FIREBASE_AUTH_DOMAIN=wizcoachdb.firebaseapp.com
FIREBASE_PROJECT_ID=wizcoachdb
FIREBASE_STORAGE_BUCKET=wizcoachdb.firebasestorage.app
FIREBASE_MESSAGING_SENDER_ID=289172482586
FIREBASE_APP_ID=1:289172482586:web:a3635f9c17161d0051ffa3

# Disable DataSource auto-config since using Firebase
spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration