# Application Configuration
server.port=${SERVER_PORT:8080}

# Python API configuration
python.api.url=${PYTHON_API_URL:http://localhost:8000}
python.api.port=${PYTHON_API_PORT:8000}
python.file.path = ${PYTHON_FILE_PATH:/src/main/resources/AI/AI_ImageAnalyzer.py}

# prompt
prompt.food_analyzer=${PROMPT_FOOD_ANALYZER:food_analyze_prompt}

# Remote API configuration
remote.api.key=${REMOTE_API_KEY:}
remote.api.base_url=${REMOTE_API_BASE_URL:}
remote.api.model=${REMOTE_API_MODEL:}

# Local Ollama API configuration
local.api.url=${LOCAL_API_URL:http://localhost:11434}
local.api.model=${LOCAL_API_MODEL:llava}

# Database Configuration (if using H2 in-memory database)
spring.datasource.url=jdbc:h2:mem:testdb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

# JPA/Hibernate Configuration
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.show-sql=true

# H2 Console (for development only)
spring.h2.console.enabled=true

# Logging
logging.level.edu.farmingdale.CSC490=DEBUG
logging.level.org.springframework.web=INFO
