# Application Configuration

# Server
server.port=${SERVER_PORT:8080}
spring.application.name=AEye-Systems

# Python API configuration
python.api.url=${PYTHON_API_URL:http://localhost:8000}
python.api.port=${PYTHON_API_PORT:8000}
python.file.path = ${PYTHON_FILE_PATH:/src/main/resources/AI/AI_ImageAnalyzer.py}

# prompt
prompt.food_analyzer=${PROMPT_FOOD_ANALYZER:food_analyze_prompt}

# Remote API configuration
REMOTE_API_KEY =
REMOTE_API_BASE_URL=
REMOTE_API_MODEL=

# Local Ollama API configuration
LOCAL_API_URL=http://localhost:11434
LOCAL_API_MODEL=llava

# Database Configuration (if using H2 in-memory database)
spring.datasource.url=jdbc:h2:mem:testdb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

# JPA/Hibernate Configuration
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
# JPA - set to none since Firebase handles your database
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true

# H2 Console (for development only)
spring.h2.console.enabled=true

# Logging
logging.level.edu.farmingdale.CSC490=DEBUG
logging.level.org.springframework.web=INFO


# Firebase
firebase.config.path=firebase-key.json

# Disable DataSource auto-config since using Firebase
spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration